#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v20
# autospec commit: f35655a
#
Name     : R-credentials
Version  : 2.0.2
Release  : 16
URL      : https://cran.r-project.org/src/contrib/credentials_2.0.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/credentials_2.0.2.tar.gz
Summary  : Tools for Managing SSH and Git Credentials
Group    : Development/Tools
License  : MIT
Requires: R-askpass
Requires: R-curl
Requires: R-jsonlite
Requires: R-openssl
Requires: R-sys
BuildRequires : R-askpass
BuildRequires : R-curl
BuildRequires : R-jsonlite
BuildRequires : R-openssl
BuildRequires : R-sys
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
other services. For HTTPS remotes the package interfaces the 'git-credential' 
    utility which 'git' uses to store HTTP usernames and passwords. For SSH 
    remotes we provide convenient functions to find or generate appropriate SSH 
    keys. The package both helps the user to setup a local git installation, and
    also provides a back-end for git/ssh client libraries to authenticate with 
    existing user credentials.

%prep
%setup -q -n credentials
pushd ..
cp -a credentials buildavx2
popd
pushd ..
cp -a credentials buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1728051074

%install
export SOURCE_DATE_EPOCH=1728051074
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/credentials/DESCRIPTION
/usr/lib64/R/library/credentials/INDEX
/usr/lib64/R/library/credentials/LICENSE
/usr/lib64/R/library/credentials/Meta/Rd.rds
/usr/lib64/R/library/credentials/Meta/features.rds
/usr/lib64/R/library/credentials/Meta/hsearch.rds
/usr/lib64/R/library/credentials/Meta/links.rds
/usr/lib64/R/library/credentials/Meta/nsInfo.rds
/usr/lib64/R/library/credentials/Meta/package.rds
/usr/lib64/R/library/credentials/Meta/vignette.rds
/usr/lib64/R/library/credentials/NAMESPACE
/usr/lib64/R/library/credentials/NEWS
/usr/lib64/R/library/credentials/R/credentials
/usr/lib64/R/library/credentials/R/credentials.rdb
/usr/lib64/R/library/credentials/R/credentials.rdx
/usr/lib64/R/library/credentials/WORDLIST
/usr/lib64/R/library/credentials/ask_token.sh
/usr/lib64/R/library/credentials/doc/index.html
/usr/lib64/R/library/credentials/doc/intro.Rmd
/usr/lib64/R/library/credentials/doc/intro.html
/usr/lib64/R/library/credentials/help/AnIndex
/usr/lib64/R/library/credentials/help/aliases.rds
/usr/lib64/R/library/credentials/help/credentials.rdb
/usr/lib64/R/library/credentials/help/credentials.rdx
/usr/lib64/R/library/credentials/help/figures/logo.png
/usr/lib64/R/library/credentials/help/paths.rds
/usr/lib64/R/library/credentials/html/00Index.html
/usr/lib64/R/library/credentials/html/R.css
